### ISSUE TITLE
Make Data Description Table

### ISSUE THREAD

**Issue by makenadlugos** [makenadlugos/QMB210-13-Group2#1]
based on administered survey

**Comment by makenadlugos** [comment]
@BrendenCarmella have you started this, do you need any help?

**Comment by BrendenCarmella** [comment]
Yes, I actually just finished. I am working on my script for what I will say in the video.

**Comment by makenadlugos** [comment]
Great job with the data description table/interpretation. Just screen record your excel while explaining your interpretation (use Zoom), and send to me!
