### ISSUE TITLE
Make Two Frequency Tables

### ISSUE THREAD

**Issue by makenadlugos** [makenadlugos/QMB210-13-Group2#2]
based on administered survey

**Comment by kellyaatwood** [comment]
I finished my frequency table, I just need to do my interpretation of the table!

**Comment by makenadlugos** [comment]
@jnierenberg I see you finished things, are you all set? any questions?

**Comment by kellyaatwood** [comment]
Also just wanted to let you know all the raw data is plugged in!

**Comment by jnierenberg** [comment]
@makenadlugos Yes! referenced the raw data and completed all my tasks. The interpretation if in the excel sheet.

**Comment by kellyaatwood** [comment]
I have my interpretation done. Should I put it on the excel?

**Comment by makenadlugos** [comment]
Thank you! Good job with your tables/interpretation. The interpretation doesn't have to be in excel, but read along with your table when you record. I'm going to close this ticket, but please submit your videos when done (email works)!
