### ISSUE TITLE
Make Contingency Table

### ISSUE THREAD

**Issue by makenadlugos** [makenadlugos/QMB210-13-Group2#3]

**Comment by NelsonHernandez1998** [comment]
waiting for data to do the table. should be done by Friday evening.

**Comment by NelsonHernandez1998** [comment]
Sorry for the late notice, but I finished both contingency tables yesterday.

**Comment by makenadlugos** [comment]
No problem thank you! I’m not sure we’ll be able to get everyone together at once, can you please send me a video of your excel and interpretation. This should be done one zoom to keep the format the same. You can record a solo meeting where you share the excel screen and read your interpretation to explain it. I’ll then put all the videos together and submit!

Sent from my iPhone

On Oct 21, 2023, at 1:28 PM, NelsonHernandez1998 ***@***.***> wrote:

﻿

Sorry for the late notice, but I finished both contingency tables yesterday.

**Comment by NelsonHernandez1998** [comment]
I don't know how to do that, but I'll try to figure it out.

**Comment by NelsonHernandez1998** [comment]
Ok, so I just finished making the video. Do I send it through email or through here on github?

**Comment by makenadlugos** [comment]
I just received your video. Looks good! I will add it to make the full clip of our project. Thank you for your work on the contingency table and doing everything in a timely manner, much appreciated!
