### ISSUE TITLE
Work on 4 Bar Charts

### ISSUE THREAD

**Issue by makenadlugos** [makenadlugos/QMB210-13-Group2#4]

**Comment by BrendanWLowe** [comment]
Working on chart right, waiting on raw data sheet

**Comment by StephenCupo** [comment]
working hard on our bar charts.

**Comment by BrendanWLowe** [comment]
Finished my two charts.  DId a bar chart and vertical chart for the raw data from Delaware and Rick Thomas parking garage.

**Comment by StephenCupo** [comment]
finished chart #2, if anything needs to be fixed or added please let me know.

**Comment by makenadlugos** [comment]
Looks good! Remember to mention which chart you did in your video. I'm going to close this ticket since everything on excel is done. Just record your interpretation with the tables you made (on zoom) and send to me to put in the video!
